### PR TITLE
work with tests that have no method source 

### PR DESCRIPTION
**Pull request by christophsturm**
this makes pitest work again with minutest 1.10+

### CODE REVIEW

**Comment by hcoles** [comment]
Thanks, sorry for slow response. if you can add a test demonstrating why the change is needed I'll merge it in.

**Comment by nicerloop** [comment]
See https://github.com/pitest/pitest-junit5-plugin/pull/43
What sort of test do you prefer? And example using cucumber?

**Comment by christophsturm** [comment]
This is really hard to test without adding a Kotlin and minutest dependency or mocking the junit api. 

Von meinem iPad gesendet

**Comment by nicerloop** [comment]
I can add a cucumber test example with corresponding dependency, I already have it.

**Comment by hcoles** [comment]
@christophsturm Thanks for your work on this, I'm closing it on the assumption that #43 supersedes it. If that is not the case, and there is still an issue with minutest feel free to re-open.

**Pull request closed without merging**
