### PR TITLE
Fixed #31 - JUnit 5 Test Cases with same name in Nested Classes are i…

### LINKED ISSUE #31: JUnit 5 Test Cases with same name in Nested Classes are ignored for creating mutations
Environment:
* PI Test 1.4.9
* pitest-junit4-plugin: 0.9
* JDK 11 / JDK 8

Problem:
* Running PI Test with pitest-junit5-plugin 
* Running Nested JUnit 5 Tests

* Example Project:
* https://github.com/khmarbaise/precondition

Description:
On the `master` of the example project you can create PI Test via
`mvn clean package  org.pitest:pitest-maven:mutationCoverage` which unfortunately shows that the `Precondition` class has some mutations which have survived.

If you change onto the `WORKING` branch you see that only the Test class has been changed in that way that I have removed the nested classes (changed method names) and produces correct results which means no mutation does survive.

At the moment I'm not sure if this located in the pitest-junit5-plugin or in PI Test itself

### PR DESCRIPTION
**Pull request by khmarbaise**
…gnored for creating mutations

### CODE REVIEW

**Comment by EugeneLesnov** [comment]
the problem is still relevant.

**Comment by khmarbaise** [comment]
Thanks for merging.

**Comment by tobiasstadler** [comment]
@khmarbaise Thank You for your fix.

@hcoles Could you do a release please?

**Comment by hcoles** [comment]
@tobiasstadler There looks to be an issue with the release plugin after its version was bumped, now getting a NoClassDefFoundError on release:prepare.

**Comment by khmarbaise** [comment]
Can you post the whole output and how you called Maven?

**Comment by khmarbaise** [comment]
Can you also show which version of maven-release-plugin you are using?

**Pull request merged**
