### PR TITLE
Simplify Gradle configuration for Gradle 1.4.7+

### PR DESCRIPTION
**Pull request by szpak**
More information:
https://blog.solidsoft.pl/2020/02/27/pit-junit-5-and-gradle-with-just-one-extra-line-of-configuration/

### CODE REVIEW

**Comment by szpak** [comment]
@hcoles Could you merge this small change in README, potentially useful for Gradle users?

**Comment by szpak** [comment]
@hcoles Any chance to make it merged as well? ;-)

**Comment by elexx** [comment]
Any chance to get this PR merged?

**Comment by hcoles** [comment]
Now merged, sorry for the delay folk.

**Pull request merged**
